apiVersion: v1
kind: Pod
metadata:
  name: tti301-lembretes
spec:
  containers:
    - name: tti301-lembretes
      image: lcstuber/tti301-lembretes
      resources:
        limits:
          memory: 256Mi
          cpu: 1